CREATE TABLE EMPLEADOS(
ID_EMPLEADO NUMBER PRIMARY KEY,
NUMERO_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO NVARCHAR2(100),
ROL NVARCHAR2(100),
SALARIO NUMBER,
HORAS NUMBER,
DIASPORSEMANA NUMBER,
BONOENTREGA NUMBER,
BONOPORHORA NUMBER,
ISR NUMBER,
VALESDESPENSA NUMBER,
MES NVARCHAR2(100)
);

INSERT INTO EMPLEADOS (NUMERO_EMPLEADO,NOMBRE,APELLIDO,ROL,SALARIO,HORAS,DIASPORSEMANA,BONOENTREGA,BONOPORHORA,ISR,VALESDESPENSA,MES) VALUES (1,'Raul','Morales Martinez','Auxiliar',5760,8,6,10,0,9,4,'Enero');
COMMIT;
SELECT * FROM EMPLEADOS where mes = 'Enero';


CREATE TABLE CAPTURAS(
ID_CAPTURA NUMBER PRIMARY KEY,
MES NVARCHAR2(100),
CANTIDAD_ENTREGAS NUMBER,
ID_EMPLEADO,
CONSTRAINT FK_CAPTURAS_EMPLEADOS FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

INSERT INTO CAPTURAS (MES,CANTIDAD_ENTREGAS,ID_EMPLEADO) VALUES ('Enero',9,2);
COMMIT;

SELECT * FROM CAPTURAS;


